// <auto-generated />
using System;
using Lab2._3.Dat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2._3.Migrations
{
    [DbContext(typeof(MusicStoreContext))]
    [Migration("20260324090238_AddAlbumDescription")]
    partial class AddAlbumDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2._3.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrackCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            GenreId = 1,
                            Price = 14.99m,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Side of the Moon",
                            TrackCount = 10
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            GenreId = 1,
                            Price = 13.99m,
                            ReleaseDate = new DateTime(1975, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wish You Were Here",
                            TrackCount = 5
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            GenreId = 2,
                            Price = 11.99m,
                            ReleaseDate = new DateTime(1959, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kind of Blue",
                            TrackCount = 5
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            GenreId = 2,
                            Price = 12.99m,
                            ReleaseDate = new DateTime(1970, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bitches Brew",
                            TrackCount = 6
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            GenreId = 3,
                            Price = 16.99m,
                            ReleaseDate = new DateTime(2013, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Random Access Memories",
                            TrackCount = 13
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            GenreId = 3,
                            Price = 12.99m,
                            ReleaseDate = new DateTime(2001, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Discovery",
                            TrackCount = 14
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 4,
                            GenreId = 4,
                            Price = 14.49m,
                            ReleaseDate = new DateTime(2017, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DAMN.",
                            TrackCount = 14
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 4,
                            GenreId = 4,
                            Price = 15.99m,
                            ReleaseDate = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Pimp a Butterfly",
                            TrackCount = 16
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 5,
                            GenreId = 1,
                            Price = 14.99m,
                            ReleaseDate = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "OK Computer",
                            TrackCount = 12
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 5,
                            GenreId = 3,
                            Price = 13.99m,
                            ReleaseDate = new DateTime(2000, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kid A",
                            TrackCount = 10
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 5,
                            GenreId = 1,
                            Price = 12.99m,
                            ReleaseDate = new DateTime(2007, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "In Rainbows",
                            TrackCount = 10
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 1,
                            GenreId = 1,
                            Price = 18.99m,
                            ReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wall",
                            TrackCount = 26
                        });
                });

            modelBuilder.Entity("Lab2._3.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DebutYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "UK",
                            DebutYear = 1965,
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            DebutYear = 1944,
                            Name = "Miles Davis"
                        },
                        new
                        {
                            Id = 3,
                            Country = "France",
                            DebutYear = 1993,
                            Name = "Daft Punk"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            DebutYear = 2004,
                            Name = "Kendrick Lamar"
                        },
                        new
                        {
                            Id = 5,
                            Country = "UK",
                            DebutYear = 1985,
                            Name = "Radiohead"
                        });
                });

            modelBuilder.Entity("Lab2._3.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hip-Hop"
                        });
                });

            modelBuilder.Entity("Lab2._3.Models.Album", b =>
                {
                    b.HasOne("Lab2._3.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2._3.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Lab2._3.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Lab2._3.Models.Genre", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
